import type { CrudConfig } from "./CrudPage";

const OWNER_TYPE_OPTIONS = [
  { value: "general_material", label: "General material" },
  { value: "supplier_grade", label: "Supplier grade" },
];

const OWNER_POLY = {
  general_material: { table: "general_materials", labelKey: "name" },
  supplier_grade: { table: "supplier_material_grades", labelKey: "grade_name" },
} as const;

export const CRUD_CONFIGS: Record<string, CrudConfig> = {
  categories: {
    table: "material_categories",
    title: "Material Categories",
    singular: "Category",
    orderBy: "name",
    orderAsc: true,
    listColumns: ["name", "slug", "parent_id"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      {
        key: "parent_id",
        label: "Parent category",
        type: "fk",
        fkTable: "material_categories",
        fkLabelKey: "name",
      },
    ],
  },
  applications: {
    table: "applications",
    title: "Applications",
    singular: "Application",
    orderBy: "name",
    orderAsc: true,
    listColumns: ["name", "industry"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "industry", label: "Industry", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  regulations: {
    table: "regulations",
    title: "Regulations",
    singular: "Regulation",
    orderBy: "name",
    orderAsc: true,
    listColumns: ["name", "region"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "region", label: "Region", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  certifications: {
    table: "certifications",
    title: "Certifications",
    singular: "Certification",
    orderBy: "name",
    orderAsc: true,
    listColumns: ["name", "issuing_body", "region"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "issuing_body", label: "Issuing body", type: "text" },
      { key: "region", label: "Region", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  sources: {
    table: "sources",
    title: "Sources",
    singular: "Source",
    orderBy: "publication_year",
    orderAsc: false,
    listColumns: ["title", "source_type", "publication_year"],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      {
        key: "source_type",
        label: "Type",
        type: "select",
        options: [
          { value: "journal", label: "Journal" },
          { value: "book", label: "Book" },
          { value: "standard", label: "Standard" },
          { value: "database", label: "Database" },
          { value: "web", label: "Web" },
          { value: "supplier", label: "Supplier document" },
          { value: "other", label: "Other" },
        ],
      },
      { key: "url", label: "URL", type: "text" },
      { key: "doi", label: "DOI", type: "text" },
      { key: "organization", label: "Organization", type: "text" },
      { key: "publication_year", label: "Publication year", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  companies: {
    table: "companies",
    title: "Companies",
    singular: "Company",
    orderBy: "company_name",
    orderAsc: true,
    listColumns: ["company_name", "country", "company_type", "verified_status"],
    fields: [
      { key: "company_name", label: "Company name", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text" },
      { key: "logo_url", label: "Logo URL", type: "text" },
      { key: "country", label: "Country", type: "text" },
      { key: "website", label: "Website", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "sustainability_focus", label: "Sustainability focus", type: "textarea" },
      {
        key: "company_type",
        label: "Type",
        type: "select",
        options: [
          { value: "producer", label: "Producer" },
          { value: "buyer", label: "Buyer" },
          { value: "other", label: "Other" },
        ],
        defaultValue: "producer",
      },
      {
        key: "verified_status",
        label: "Verified status",
        type: "select",
        options: [
          { value: "pending", label: "Pending" },
          { value: "approved", label: "Approved" },
          { value: "rejected", label: "Rejected" },
        ],
        defaultValue: "pending",
      },
    ],
  },
  materials: {
    table: "general_materials",
    title: "General Materials",
    singular: "Material",
    orderBy: "name",
    orderAsc: true,
    listColumns: ["name", "slug", "category_id", "status", "data_confidence"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "short_description", label: "Short description", type: "textarea" },
      {
        key: "category_id",
        label: "Category",
        type: "fk",
        fkTable: "material_categories",
        fkLabelKey: "name",
      },
      { key: "chemical_formula", label: "Chemical formula", type: "text" },
      { key: "chemical_structure_url", label: "Chemical structure URL", type: "text" },
      { key: "sustainability_summary", label: "Sustainability summary", type: "textarea" },
      { key: "end_of_life_summary", label: "End-of-life summary", type: "textarea" },
      { key: "production_scale_maturity", label: "Production scale maturity", type: "text" },
      {
        key: "data_confidence",
        label: "Data confidence",
        type: "select",
        options: [
          { value: "high", label: "High" },
          { value: "medium", label: "Medium" },
          { value: "low", label: "Low" },
          { value: "ai_assisted", label: "AI-assisted" },
          { value: "literature", label: "Literature-backed" },
          { value: "supplier_reported", label: "Supplier-reported" },
        ],
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "draft", label: "Draft" },
          { value: "published", label: "Published" },
        ],
        defaultValue: "draft",
      },
    ],
  },
  synonyms: {
    table: "general_material_synonyms",
    title: "Material Synonyms",
    singular: "Synonym",
    orderBy: "created_at",
    listColumns: ["material_id", "synonym"],
    fields: [
      {
        key: "material_id",
        label: "Material",
        type: "fk",
        fkTable: "general_materials",
        fkLabelKey: "name",
        required: true,
      },
      { key: "synonym", label: "Synonym", type: "text", required: true },
    ],
  },
  tags: {
    table: "general_material_tags",
    title: "Material Tags",
    singular: "Tag",
    orderBy: "created_at",
    listColumns: ["material_id", "tag"],
    fields: [
      {
        key: "material_id",
        label: "Material",
        type: "fk",
        fkTable: "general_materials",
        fkLabelKey: "name",
        required: true,
      },
      { key: "tag", label: "Tag", type: "text", required: true },
    ],
  },
  grades: {
    table: "supplier_material_grades",
    title: "Supplier Material Grades",
    singular: "Grade",
    orderBy: "grade_name",
    orderAsc: true,
    listColumns: [
      "grade_name",
      "general_material_id",
      "company_id",
      "status",
      "verified_status",
    ],
    fields: [
      { key: "grade_name", label: "Grade name", type: "text", required: true },
      {
        key: "general_material_id",
        label: "General material",
        type: "fk",
        fkTable: "general_materials",
        fkLabelKey: "name",
        required: true,
      },
      {
        key: "company_id",
        label: "Company",
        type: "fk",
        fkTable: "companies",
        fkLabelKey: "company_name",
        required: true,
      },
      { key: "description", label: "Description", type: "textarea" },
      { key: "production_scale", label: "Production scale", type: "text" },
      {
        key: "availability_type",
        label: "Availability",
        type: "select",
        options: [
          { value: "wholesale", label: "Wholesale" },
          { value: "on_demand", label: "On demand" },
          { value: "pilot", label: "Pilot" },
          { value: "industrial", label: "Industrial" },
        ],
      },
      { key: "moq", label: "MOQ", type: "text" },
      { key: "country_of_production", label: "Country of production", type: "text" },
      { key: "uniqueness", label: "Uniqueness / USP", type: "textarea" },
      { key: "datasheet_url", label: "Datasheet URL", type: "text" },
      {
        key: "premium_visibility",
        label: "Visible to premium",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "verified_status",
        label: "Verified status",
        type: "select",
        options: [
          { value: "pending", label: "Pending" },
          { value: "approved", label: "Approved" },
          { value: "rejected", label: "Rejected" },
        ],
        defaultValue: "pending",
      },
      {
        key: "status",
        label: "Publish status",
        type: "select",
        options: [
          { value: "draft", label: "Draft" },
          { value: "pending_review", label: "Pending review" },
          { value: "approved", label: "Approved" },
          { value: "rejected", label: "Rejected" },
        ],
        defaultValue: "draft",
      },
    ],
  },
  properties: {
    table: "material_properties",
    title: "Material Properties",
    singular: "Property",
    orderBy: "created_at",
    listColumns: ["owner_type", "owner_id", "property_name", "unit"],
    fields: [
      {
        key: "owner_type",
        label: "Owner type",
        type: "select",
        options: OWNER_TYPE_OPTIONS,
        required: true,
      },
      {
        key: "owner_id",
        label: "Owner",
        type: "fk-poly",
        dependsOn: "owner_type",
        polyMap: OWNER_POLY,
        required: true,
      },
      { key: "property_name", label: "Property name", type: "text", required: true },
      { key: "value_min", label: "Min value", type: "number" },
      { key: "value_max", label: "Max value", type: "number" },
      { key: "exact_value", label: "Exact value", type: "number" },
      { key: "unit", label: "Unit", type: "text" },
      { key: "test_standard", label: "Test standard", type: "text" },
      {
        key: "source_id",
        label: "Source",
        type: "fk",
        fkTable: "sources",
        fkLabelKey: "title",
      },
      { key: "confidence_level", label: "Confidence level", type: "text" },
    ],
  },
  "material-applications": {
    table: "material_applications",
    title: "Material ↔ Application Links",
    singular: "Link",
    orderBy: "created_at",
    listColumns: ["owner_type", "owner_id", "application_id"],
    fields: [
      {
        key: "owner_type",
        label: "Owner type",
        type: "select",
        options: OWNER_TYPE_OPTIONS,
        required: true,
      },
      {
        key: "owner_id",
        label: "Owner",
        type: "fk-poly",
        dependsOn: "owner_type",
        polyMap: OWNER_POLY,
        required: true,
      },
      {
        key: "application_id",
        label: "Application",
        type: "fk",
        fkTable: "applications",
        fkLabelKey: "name",
        required: true,
      },
    ],
  },
  "material-regulations": {
    table: "material_regulations",
    title: "Material ↔ Regulation Links",
    singular: "Link",
    orderBy: "created_at",
    listColumns: ["owner_type", "owner_id", "regulation_id", "status"],
    fields: [
      {
        key: "owner_type",
        label: "Owner type",
        type: "select",
        options: OWNER_TYPE_OPTIONS,
        required: true,
      },
      {
        key: "owner_id",
        label: "Owner",
        type: "fk-poly",
        dependsOn: "owner_type",
        polyMap: OWNER_POLY,
        required: true,
      },
      {
        key: "regulation_id",
        label: "Regulation",
        type: "fk",
        fkTable: "regulations",
        fkLabelKey: "name",
        required: true,
      },
      { key: "status", label: "Status", type: "text" },
      { key: "evidence_url", label: "Evidence URL", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  "material-certifications": {
    table: "material_certifications",
    title: "Material ↔ Certification Links",
    singular: "Link",
    orderBy: "created_at",
    listColumns: ["owner_type", "owner_id", "certification_id", "status", "expiry_date"],
    fields: [
      {
        key: "owner_type",
        label: "Owner type",
        type: "select",
        options: OWNER_TYPE_OPTIONS,
        required: true,
      },
      {
        key: "owner_id",
        label: "Owner",
        type: "fk-poly",
        dependsOn: "owner_type",
        polyMap: OWNER_POLY,
        required: true,
      },
      {
        key: "certification_id",
        label: "Certification",
        type: "fk",
        fkTable: "certifications",
        fkLabelKey: "name",
        required: true,
      },
      { key: "status", label: "Status", type: "text" },
      { key: "document_url", label: "Document URL", type: "text" },
      { key: "expiry_date", label: "Expiry date", type: "date" },
    ],
  },
  sustainability: {
    table: "sustainability_indicators",
    title: "Sustainability Indicators",
    singular: "Record",
    orderBy: "created_at",
    listColumns: [
      "owner_type",
      "owner_id",
      "bio_based_content",
      "carbon_footprint_value",
      "carbon_footprint_unit",
    ],
    fields: [
      {
        key: "owner_type",
        label: "Owner type",
        type: "select",
        options: OWNER_TYPE_OPTIONS,
        required: true,
      },
      {
        key: "owner_id",
        label: "Owner",
        type: "fk-poly",
        dependsOn: "owner_type",
        polyMap: OWNER_POLY,
        required: true,
      },
      { key: "bio_based_content", label: "Bio-based content (%)", type: "number" },
      { key: "recycled_content", label: "Recycled content (%)", type: "number" },
      { key: "carbon_footprint_value", label: "Carbon footprint", type: "number" },
      { key: "carbon_footprint_unit", label: "CO₂ unit", type: "text" },
      { key: "lca_available", label: "LCA available", type: "boolean" },
      { key: "epd_available", label: "EPD available", type: "boolean" },
      { key: "carbon_credits", label: "Carbon credits", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  "ai-drafts": {
    table: "ai_material_drafts",
    title: "AI Material Drafts",
    singular: "Draft",
    orderBy: "created_at",
    listColumns: ["general_material_id", "model", "status"],
    fields: [
      {
        key: "general_material_id",
        label: "Linked material",
        type: "fk",
        fkTable: "general_materials",
        fkLabelKey: "name",
      },
      { key: "prompt", label: "Prompt", type: "textarea" },
      { key: "generated_payload", label: "Generated payload (JSON)", type: "json" },
      { key: "model", label: "Model", type: "text" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "pending", label: "Pending" },
          { value: "approved", label: "Approved" },
          { value: "rejected", label: "Rejected" },
        ],
        defaultValue: "pending",
      },
    ],
  },
};

export const ADMIN_NAV: {
  section: string;
  items: { slug: string; label: string }[];
}[] = [
  {
    section: "Content",
    items: [
      { slug: "materials", label: "General Materials" },
      { slug: "synonyms", label: "Synonyms" },
      { slug: "tags", label: "Tags" },
      { slug: "properties", label: "Properties" },
      { slug: "sustainability", label: "Sustainability" },
    ],
  },
  {
    section: "Taxonomy",
    items: [
      { slug: "categories", label: "Categories" },
      { slug: "applications", label: "Applications" },
      { slug: "regulations", label: "Regulations" },
      { slug: "certifications", label: "Certifications" },
      { slug: "sources", label: "Sources" },
    ],
  },
  {
    section: "Links",
    items: [
      { slug: "material-applications", label: "Material ↔ Applications" },
      { slug: "material-regulations", label: "Material ↔ Regulations" },
      { slug: "material-certifications", label: "Material ↔ Certifications" },
    ],
  },
  {
    section: "Suppliers",
    items: [
      { slug: "companies", label: "Companies" },
      { slug: "grades", label: "Supplier Grades" },
    ],
  },
  {
    section: "System",
    items: [{ slug: "ai-drafts", label: "AI Drafts" }],
  },
];